### ISSUE TITLE
Excellent design

### ISSUE THREAD

**Issue by jema28** [FACK1/Beauty#46]
I'm really impressed by your design this week - very beautiful interface / consistent design ✨ 

1. The colour scheme is well thought out (did you use a design resource site for this)? I like how you've picked one colour throughout and not overcomplicated things ❤️

2. I love the modern font you've used, it fits with the context of beauty. Again it's about simplicity (simplicity done well is a great thing! 💯)

Great job!

**Comment by mattlub** [comment]
+ responsiveness! 👍

**Comment by mattlub** [comment]
\+ did you think about using CSS variables for your colour scheme?

**Comment by mattlub** [comment]
@RazanTayyem you are using the same colour quite a few times. I meant something like:

```css
html {
  --colour-primary: #13dh32;
}

.title {
  color: var(--colour-primary);
}

.product-container {
  border: 1px solid var(--colour-primary);
}
```
